- name: ":date: Communication:Meeting"
  description: Need to communicate via Meeting (Optional)
  color: ffccf3
- name: ":seedling: Communication:FailureKnowledge"
  description: Learning Cases from any failed experience (Optional)
  color: ffccf3
- name: ":mega: Communication:VoiceOfCustomer"
  description: Directly linked to Voice Of Customer (Optional)
  color: ffccf3
- name: ":briefcase: Domain:Business"
  description: About a business-related idea/problem issue affected on the entire organization
  color: c2e0c6
- name: ":desktop_computer: Domain:Infra"
  description: About an infra or a project-related idea/problem issue based on a specific repository
  color: c2e0c6
- name: ":iphone: Domain:UX"
  description: About an userstory issue based on a specific repository
  color: c2e0c6
- name: ":turtle: ETR:1M+"
  description: Estimated Time of Resolution is about 1 Month or more
  color: 079b27
- name: ":airplane: ETR:1W-"
  description: Estimated Time of Resolution is 1 Week or less
  color: 079b27
- name: ":blue_car: ETR:1W+"
  description: Estimated Time of Resolution is 1 Week or more but less than 1 Month
  color: 079b27
- name: ":shrug: Judge:Deprecated"
  description: Duplicated or altered to another issue or do not need to solve
  color: edcf2a
- name: ":exclamation: Judge:Policy"
  description: Policies for this entire organization
  color: edcf2a
- name: ":red_square: Priority:Emergency"
  description: Priority depends on service on-going or focusing resources at that time
  color: f900aa
- name: ":orange_square: Priority:High"
  description: Priority depends on service on-going or focusing resources at that time
  color: f900aa
- name: ":brown_square: Priority:Low"
  description: Priority depends on service on-going or focusing resources at that time
  color: f900aa
- name: ":blue_square: Priority:Medium"
  description: Priority depends on service on-going or focusing resources at that time
  color: f900aa
- name: ":lady_beetle: Task:Bug"
  description: Something isn't working
  color: 063FBB
- name: ":memo: Task:Documentation"
  description: Improvements or additions to documentation
  color: 063FBB
- name: ":rocket: Task:Enhancement"
  description: New feature or an issue to make something better
  color: 063FBB
